### ISSUE TITLE
Questions about license

### ISSUE THREAD

**Issue by Junsang-Mun** [dotleon/cheapis#1]
Hey, thanks for sharing your lovely work.

I got some ideas inspired by your CHEAPIS, so I'm willing to improve some details if allowed.
So the question what is the license of this work? Am I free to modify/publish/or sell - Of course I am not going sell this, but just asking for someone - ?

**Comment by dotleon** [comment]
Hey,

I've added the GNU GPLv3 license, which lets people do almost anything they want with the project, except distributing closed source versions.
