### ISSUE TITLE
Advice on firmware?

### ISSUE THREAD

**Issue by lubekpl** [dotleon/cheapis#2]
Do you have any insight on firmware? Is sweep's firmware compatible?

**Comment by dotleon** [comment]
I doubt sweep's firmware is compatible, especially as this is not a two controller setup, and is using a matrix intead of direct pins.

Here's a working vial firmware you can build:

https://github.com/dotleon/vial-qmk/tree/dotleonkeebs/keyboards/cheapis

**Comment by lubekpl** [comment]
Thanks!
